### ISSUE TITLE
GetV1Incidents call fails

### ISSUE THREAD

**Issue by srikotu** [firehydrant/api-client-go#49]
Seems like json unmarshalling is breaking for retro_exports field.

I am trying to make a call to incidents.ClientService.GetV1Incidents(), I am able to get responses for the first page which doesn't have any retro_export objects but it breaks for the second page as soon as it reads the retro_export object.

Below is the error that is returned by the function call:
```json: cannot unmarshal object into Go struct field IncidentEntity.data.retro_exports of type string```

**Comment by wilsonehusin** [comment]
👋🏻 @srikotu thanks for reporting the bug — we've updated the entity type in #58, but looks like you may still need to unmarshal the underlying `interface{}` to `map[string]interface{}` with something like [mitchellh/mapstructure](https://pkg.go.dev/github.com/mitchellh/mapstructure).

**Comment by srikotu** [comment]
@wilsonehusin thank you for replying back with the update. I have been able to use the updated spec and it works perfectly. 

Thanks for the quick resolution.
